######################################################################
##
## Filename: clk_div_tb.udo
## Created on: Tue Apr 16 9:49:02 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
