######################################################################
##
## Filename: log_tb.udo
## Created on: Tue Apr 16 13:03:46 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
