######################################################################
##
## Filename: pipe_if_tb.udo
## Created on: Mon Apr 22 14:38:13 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
