######################################################################
##
## Filename: ram_writefirst_tb.udo
## Created on: Sun Apr 21 10:53:28 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
