######################################################################
##
## Filename: alu.udo
## Created on: Tue Apr 23 19:32:20 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
