######################################################################
##
## Filename: bshifter32_carry_tb.udo
## Created on: Thu Apr 25 8:36:30 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
