######################################################################
##
## Filename: ext_tb.udo
## Created on: Wed Apr 24 15:42:13 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
