######################################################################
##
## Filename: sltsltu_tb.udo
## Created on: Tue Apr 30 18:57:42 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
